vim.print("Running scripts/install.lua")
vim.system({ "notify-send", "Running scripts/install.lua" })
require('blink.cmp.fuzzy.build').build()
vim.print("... scripts/install.lua after build")
vim.system({ "notify-send", "... scripts/install.lua after build" })
